### ISSUE TITLE
Compiling Most Recent Commit

### ISSUE THREAD

**Issue by Dr-Crow** [fail0verflow/hbc#15]
I have been trying to compile the most recent code but keep running into the same error. I think the error has to do with the `common-key` and the way I have it formatted.

My error is:

```
python2 tools/join-imet.py channel.imet build/data.arc build/icon.arc build/banner.arc build/sound.bns names.txt
make[1]: Leaving directory '/root/test/hbc/channel/banner'
make[1]: Entering directory '/root/test/hbc/channel/title'
Warning: failed to load key korean-key
fixing Tik file retail/cetk
Incorrect AES key length (33 bytes)

Incorrect AES key length (33 bytes)

Incorrect AES key length (33 bytes)
Warning: failed to load key korean-key
updating content records of TMD file retail/tmd
Warning: failed to load key korean-key
setting version of TMD file retail/tmd to 0x0102
Warning: failed to load key korean-key

Incorrect AES key length (33 bytes)
Traceback (most recent call last):
  File "/root/test/hbc/channel/title/../../pywii/pywii-tools/wadpack.py", line 28, in <module>
    wad.adddata(data,ct.cid)
  File "/root/test/hbc/pywii/pywii-tools/pywii/wii.py", line 1509, in adddata
    raise Exception("Required key is not available")
Exception: Required key is not available
Makefile:14: recipe for target 'channel_retail.wad' failed
make[1]: *** [channel_retail.wad] Error 1
make[1]: Leaving directory '/root/test/hbc/channel/title'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2
```

The `Incorrect AES key length (33 bytes)` was generated by me printing the expectation that this block of code is generating:

https://github.com/fail0verflow/hbc/blob/c76dae814bbc6199107e62e255c50f94a484b9b2/pywii/Common/pywii/wii.py#L486-L498

I have my `common-key` located at `~/.wii/common-key`. 

@marcan I saw your comment on #11 about the `common-key` needing to be in binary? Is that true? Or does a plain text work?

**Comment by marcan** [comment]
Correct, common-key needs to be in binary and exactly 16 bytes in length.

**Comment by Dr-Crow** [comment]
@marcan Thanks for the quick response. Maybe I am a bit rusty with my python, but do you have a command handy to convert a string to the correct binary format?

I've tried:

```
import binascii
 
# Common Key String
st = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

bin(int(binascii.hexlify(st),16))
``` 

But that still give me the error of "Incorrect AES key length" .

If you have either a pythonic way to convert it or Linux, that would be helpful.

**Comment by marcan** [comment]
Try `open("common-key", "wb").write(bytes.fromhex("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"))`.
